# Generated by Django 5.2.1 on 2025-05-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='belonging',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='belonging_images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='qr_code',
            field=models.ImageField(unique=True, upload_to='qr_codes/'),
        ),
    ]
