# Generated by Django 5.2.1 on 2025-05-11 19:57

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_belonging_image_alter_student_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belonging',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.belonging_image_upload_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.student_image_upload_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='qr_code',
            field=models.ImageField(unique=True, upload_to=students.models.student_qr_code_upload_path),
        ),
    ]
