# Generated by Django 5.2.1 on 2025-05-19 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_cafeteria'),
        ('students', '0005_alter_belonging_image_alter_student_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assigned_cafeteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_students', to='meal.cafeteria'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Active'),
        ),
    ]
