# Generated by Django 5.2.1 on 2025-05-10 17:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_belonging_image_alter_student_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Scan Timestamp')),
                ('meal_type', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], max_length=1, verbose_name='Meal Type')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_records', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Meal Record',
                'verbose_name_plural': 'Meal Records',
                'ordering': ['-timestamp'],
                'unique_together': {('student', 'date', 'meal_type')},
            },
        ),
    ]
